version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    container_name: mariadb_container
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=user
      - MARIADB_DATABASE=sma
      - MARIADB_PASSWORD=password
    ports:
      - 3306:3306
